os:
  - linux
services:
  - docker
language: java
node_js:
  - "6.9.4"
jdk:
  - oraclejdk8
sudo: false
branches:
  only: 
    - master
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  - NODE_VERSION=6.9.1
before_install:
#Browser setup
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#
  - nvm install $NODE_VERSION
  - npm install -g npm
  - npm install -g bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - bower install
  - gulp -v
  - java -version
install: npm install
script:
  - ./mvnw clean
  - ./mvnw test
  - gulp test
  - ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
