version: '2'
services:
    kpics-mongodb:
        container_name: kpics-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/kpics/mongodb/:/data/db/
